# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1f3863aa83261af3e7a708cd4f9a43c13a2416d5c16af584d5fd4ef90174d5806578f3f1741908c2588fb5c1ce79afe3d42d26d6cf43670f01a3a7a16963329d

test:
  secret_key_base: b379e859e1a3b4cfbcd9247ede27655ffe00db56e3d20008888df8f07135e4483915931db714611f6e527e2150f5852d2f27bb61344801349abbe00149b74416

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
